# Generated by Django 4.2.11 on 2024-04-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
